### ISSUE TITLE
error when updating from 20.0.2 to 20.0.14

### ISSUE THREAD

**Issue by Bradley-Liu** [nextcloud/workflow_script#182]
2023-06-29T02:54:11+00:00 Checked for update of app "workflowengine" in appstore
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Circles\Migration\Version0022Date20220526111723::__construct(), 0 passed in /config/www/nextcloud/lib/private/DB/MigrationService.php on line 456 and exactly 1 expected in /config/www/nextcloud/apps/circles/lib/Migration/Version0022Date20220526111723.php:55
Stack trace:
#0 /config/www/nextcloud/lib/private/DB/MigrationService.php(456): OCA\Circles\Migration\Version0022Date20220526111723->__construct()
#1 /config/www/nextcloud/lib/private/DB/MigrationService.php(473): OC\DB\MigrationService->createInstance()
#2 /config/www/nextcloud/lib/private/DB/MigrationService.php(419): OC\DB\MigrationService->executeStep()
#3 /config/www/nextcloud/lib/private/Installer.php(590): OC\DB\MigrationService->migrate()
#4 /config/www/nextcloud/lib/private/Installer.php(544): OC\Installer::installShippedApp()
#5 /config/www/nextcloud/lib/private/Updater.php(276): OC\Installer::installShippedApps()
#6 /config/www/nextcloud/lib/private/Updater.php(132): OC\Updater->doUpgrade()
#7 /config/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#8 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#10 /config/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#11 /config/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#12 /config/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#13 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#14 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#15 {main}
Please help

**Comment by blizzz** [comment]
@Bradley-Liu the fitting place to report this would be the circles repo, but NC 20 is EOL. I'd try to disable circles and redo the upgrade. Otherwise, please discuss in the [forums](https://help.nextcloud.com).
